### ISSUE TITLE
Unable to get a new Random gif

### ISSUE THREAD

**Issue by anderseide** [Giphy/giphy-js#117]
I'm trying to use the js-fetch-api to get a random GIF. On first execute, this works fine, but when trying to get another one, I just get the same result as the previous call. Almost like it's cached or something...

```javascript
const data = await gf.random({
      tag: "thumbs up",
      type: "gifs",
      rating: "pg"
    });
```

What am I doing wrong here?
Issue reproduced here https://codesandbox.io/s/cold-bash-9o9sh

**Comment by giannif** [comment]
@anderseide this is a bug, thanks for catching, surprised it's gone so long undetected. I'll get a fix out shortly. We are caching in memory based on url.

**Comment by giannif** [comment]
@anderseide there are new packages ready. `@giphy/js-fetch-api: 1.6.1` fixes this

**Comment by brenc** [comment]
Hello - this appears to still be happening with the latest version:
https://codesandbox.io/p/devbox/polished-mountain-5976ws?workspaceId=ws_QHtRHytGXDWeGo9ndsxHhh

**Comment by giannif** [comment]
This seems to happen at the request level this time, hitting the same url gives us the same cached response. https://api.giphy.com/v1/gifs/random?rating=pg-13&api_key=kTZJJiOjyuYYJdagT26CbCqTyBMjuDor&pingback_id=19850dc8ff6ce6b9

We'll look into it
