### ISSUE TITLE
Deploying without exposing api key?

### ISSUE THREAD

**Issue by MatthewCaseres** [Giphy/giphy-js#120]
I have heard that API keys should not be passed to the client as they are then available to all visitors of the website. I am not sure how to avoid this because I need to instantiate the giphyFetch on the client side?

**Comment by giannif** [comment]
@MatthewCaseres it's not a sensitive api key in this case, I wouldn't worry about it 👍  It's on the network requests, so it being in javascript isn't a big reveal really

**Comment by kwasimensah** [comment]
This is actually dangerous because exposing the API key lets people talking the Giphy as if they were you (including spamming, misusing quota etc). 

I currently route all requests to giphy through my backend where I can hide the key from the world.

**Comment by MatthewCaseres** [comment]
I was thinking about doing that but wasn't sure how to do that with the SDK without sending the api key to their react component.

**Comment by kwasimensah** [comment]
The react components take a fetchGif async function which you can implement to talk to your server instead

**Comment by giannif** [comment]
@kwasimensah @MatthewCaseres this is really something you shouldn't be worrying about. 

Here is the official response to this question from GIPHY:

> GIPHY APIs are designed to be used on the client side (and hence the API key too). You should go ahead and use it that way. Once development is complete - please apply for Production access for the key through the Developer Dashboard, this removes Rate limits associated with a beta key, so you don't have to worry about high traffic.
Lastly, and most importantly - GIPHY has monitors setup for API key abuse and we'll reach out to you if anything happens. We definitely don't want you to worry about it.
