### ISSUE TITLE
Invalid Hook Call Error when Rendering React Giphy Grid

### ISSUE THREAD

**Issue by mallerie** [Giphy/giphy-js#137]
I'm working on a giphy integration for my app, and when I try to render, I get the invalid hook call error:

`Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See [https://fb.me/react-invalid-hook-call](https://fb.me/react-invalid-hook-call) for tips about how to debug and fix this problem.`

I have `react` and `react-dom` version 16.13.1. I know that the giphy components are using react 16.4 and I am wondering if there may be an issue with hooks not being supported by the giphy components? I tried it with a class component and got the same issue. The docs say: "Mismatching Versions of React and React DOM
You might be using a version of react-dom (< 16.8.0) or react-native (< 0.59) that doesn’t yet support Hooks."

My code:
`import React from 'react';
  import PropTypes from 'prop-types';
  import { GiphyFetch } from '@giphy/js-fetch-api';
  import { Grid } from '@giphy/react-components';

  const Giphy = () => {
    const giphyFetch = new GiphyFetch('myAPIKey');
    const fetchGifs = (offset) => giphyFetch.trending({ offset, limit: 10 });

    return (
      <React.Fragment>
        <h3>Grid Example</h3>
        <Grid fetchGifs={fetchGifs} width={500} columns={3} />
      </React.Fragment>
    );
  };`

**Comment by giannif** [comment]
Hey @mallerie the SDK definitely supports hooks, we use them in the code base. I wonder if you have two versions of React? 

Maybe you can try defining a `resolutions` in your package.json, something like
```json
  "resolutions": {
        "react": "your verson",
        "react-dom": "your verson"
    },
```

I had this error just the other day and it wasn't any of the reasons listed in the error description, so it may be something else entirely. 

Maybe you can reference our [codesandbox](https://codesandbox.io/s/giphyreact-components-hbmcf?from-embed=&file=/src/index.tsx) and compare it with your setup, though looking at the snippet, it looks pretty straightforward.

**Comment by mallerie** [comment]
That's what I am doing now. Thanks so much.
