### ISSUE TITLE
[@giphy/js-types] original_mp4 improperly typed

### ISSUE THREAD

**Issue by stopdropandrew** [Giphy/giphy-js#146]
https://github.com/Giphy/giphy-js/blob/master/packages/types/src/gif.ts#L49

`original_mp4` is typed as `IImage` but not `IMP4`. I think `IMP4` needs to extend `IRendition` and `original_mp4` would just be `IMP4`.

**Comment by giannif** [comment]
@stopdropandrew thanks for catching this, I'll work on a fix!

**Comment by stopdropandrew** [comment]
Wow thanks for the quick response!
