### ISSUE TITLE
Fetch gifs by ids doesn't always return every gif in function parameter

### ISSUE THREAD

**Issue by StephenMayeux** [Giphy/giphy-js#163]
When I use the `gf.gifs(string[])` API to fetch a list of gifs by IDs, it usually responds with all the gifs that I've requested but not always. 

I've defined a simple function in my service layer that looks like this:

``` javascript
export const getGifsByIds = async (gifIds) => {
    console.log('ids:', gifIds);
    const { data } = await gf.gifs(gifIds);
    console.log('data', data);
    return data;
};
```
And below is a screenshot of those console log statements. I'm passing in an array of 6 gif Ids, but only 5 are being returned by `gf.gifs()`. 

![Screen Shot 2021-02-22 at 5 22 22 PM](https://user-images.githubusercontent.com/13535545/108783711-9051e480-7533-11eb-8502-f526f279e368.png)

The gifId that is missing in the results is `gifIds[4]` i.e. `l0MYsHhzxfLsYfpPW`. I've confirmed it is an existing GIF by visiting `https://media.giphy.com/media/l0MYsHhzxfLsYfpPW/giphy.gif` and sure enough it's some famous sportsball player. 

Is the API working as expected or is this a bug? If it is working as expected, what is it about gif `l0MYsHhzxfLsYfpPW` that cannot be retrieved by `gf.gifs()`?

**Comment by giannif** [comment]
@StephenMayeux yeah, I've never seen that before. 

@ethanlu any idea why this returns a 404:
https://api.giphy.com/v1/gifs/l0MYsHhzxfLsYfpPW?api_key=sXpGFDGZs0Dv1mmNFvYaGUvYwKX0PWIh&pingback_id=177cf74e3c8d1cff

But the gif is public on giphy.com:
https://giphy.com/gifs/nfl-football-excited-l0MYsHhzxfLsYfpPW

**Comment by StephenMayeux** [comment]
@giannif @ethanlu Any updates on this? Please let me know, and thank you!

**Comment by ethanlu** [comment]
@StephenMayeux @giannif Hey, sorry for delayed response. We have a lot of content that must be blocked for reasons such as:
- content owner made the content private
- content owner restricted access to the content
- content owner removed the content

When any of the situations above causes the content to be no longer available, the getGifById endpoint will reply with a HTTP 404 response. Likewise, the getGifsByIds call will only return back the requested GIF IDs that are still accessible.

In this particular case, what might have happened is that NFL GIF was initially accessible to all, but was later updated to be restricted to only Giphy properties and a few other integrations. So, subsequent requests for it would no longer return it. The media URL is still accessible of course if you can get a hold of it.

This kind of accessibility restrictions can happen often, so it is best to have some logic into your code to handle this case gracefully.

**Comment by StephenMayeux** [comment]
Thank you.
