### ISSUE TITLE
Keyboard Accessibility Support

### ISSUE THREAD

**Issue by amanagr** [Giphy/giphy-js#174]
GIFs in the grid are not keyboard accessible using tab since there is no `tabindex` set for them. While setting `tabindex=0` using javascript fixes the issue, it would be nice if this was already present in the DOM element of the GIF's [`<div>`](https://github.com/Giphy/giphy-js/blob/master/packages/components/src/components/grid.tsx#L160) tag to save the unnecessary JS query.

**Comment by giannif** [comment]
@amanagr thanks for reporting this, sounds like a good thing to have for sure. Should we make this opt in as a prop? I wouldn't want to have conflicts with other tabindex values on the same page. 

Something like this?

```tsx
<Grid tabindex={10} ... />

**Comment by amanagr** [comment]
This is actually something that anyone using this on the web should have unless they want the GIFs to be non-interactive. So, if you want,  I would suggest this should ideally be an opt-out. People might want to set their custom value of `tabindex` but `tabindex=0` is a very good default value.

**Comment by giannif** [comment]
@amanagr ok, this is planned 👍 I'm on vacation the next two weeks but expect a release second week in April
