### ISSUE TITLE
Angular components

### ISSUE THREAD

**Issue by MickL** [Giphy/giphy-js#184]
As you provide React components, maybe you could do the same for the lovely Angular framework, too? :)

For example it could then widely use RxJS (for rerendering, etc) and Angular Http client and may safe a lot of bundle size while providing maximized performance using the Angular renderer. 

Wasnt much of a problem to use your js-components, tho. Love that you made it in TypeScript!

**Comment by giannif** [comment]
I'll leave this open for a bit to see if anyone else wants to vote for Angular. We don't have the bandwidth to do it at the moment, though. I kind of wrote the js-components to cover all the non-React scenarios. I'm glad it's working for you!

**Comment by MickL** [comment]
You may close this then :)

**Comment by aidosmen** [comment]
I vote as well )
