### ISSUE TITLE
Bundle for proper tree shaking / no CommonJS

### ISSUE THREAD

**Issue by MickL** [Giphy/giphy-js#186]
Importing ´import { renderGif } from '@giphy/js-components';` or `import { GiphyFetch } from '@giphy/js-fetch-api';` in Angular results in a warning:

> Warning: /....../giphy/giphy.component.ts depends on '@giphy/js-components'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Would be nice if both packages are bundled properly. Personally I use rollup for that.

**Comment by giannif** [comment]
@MickL they are bundled with the typescript compiler using module set to 'commonjs', which is what is recommended and works in SSR as well as the client. I don't think we have the bandwidth to add more build tools

**Comment by MickL** [comment]
Thats unfortunate. From the docs:

> Depending on CommonJS modules can prevent bundlers and minifiers from optimizing your application, which results in larger bundle sizes. Instead, it is recommended that you use ECMAScript modules in your entire application. For more information, see see How CommonJS is making your bundles large https://web.dev/commonjs-larger-bundles/
