### ISSUE TITLE
How to download a gif from command line?

### ISSUE THREAD

**Issue by kopax-polyconseil** [Giphy/giphy-js#188]
Hello, 

I want to post a tweet with a giphy, tweet is scheduled and tweet post api v1 is forcing us to upload the gif.

after choosing the `gif`, I have tried to `wget $gif.url` but I get a web page. How can I use that component to post a Giphy on twitter using the twitter API in delayed (scheduled) ?

Thanks!

**Comment by giannif** [comment]
@kopax-polyconseil `gif.url` is for the web page. You'll want to choose a rendition from the images object and use the url there. You can read about our renditions [here](https://developers.giphy.com/docs/api/schema#image-object)
