### ISSUE TITLE
[@giphy/js-components] Warning: Circular dependencies

### ISSUE THREAD

**Issue by huynguyen93** [Giphy/giphy-js#244]
Hello, I got a warning when bundling my code with rollupjs (code still worked)

Circular dependencies
node_modules/@giphy/js-fetch-api/dist/index.js 
-> node_modules/@giphy/js-fetch-api/dist/api.js 
-> node_modules/@giphy/js-fetch-api/dist/request.js 
-> node_modules/@giphy/js-fetch-api/dist/index.js

I see in the code, we can move this line 
https://github.com/Giphy/giphy-js/blob/7b5f51fcde83fb698a2fb7b4d34f49ba97e665ef/packages/fetch-api/src/index.ts#L7
to a new file (say constants.js) to prevent this?

If it's ok I can make a PR.

Thanks!

**Comment by giannif** [comment]
@huynguyen93 I just noticed this too! Yes, a PR is welcome if you have time today. I'm adding dependency cruiser so this doesn't happen again :)

**Comment by giannif** [comment]
Fixed in #245
