### ISSUE TITLE
How to pick the format having only the id?

### ISSUE THREAD

**Issue by geneoes** [Giphy/giphy-js#271]
Hi all!

I have a site where user posts `text`  and  `giphy gifs`,  and I been saving those posts together with the giphy id
At the moment, in order to show them I'm creating this url:

```
const source = `https://media2.giphy.com/media/${giphyId}/giphy.gif`
```

I wonder how can I start using `webp` or `mp4` formats instead.

Should I just change that url to end with `${giphyId}/giphy.webp`? in that case, all the older years posted gifs  should keep working with this new url?  

Thanks

**Comment by pshoniuk** [comment]
Hi @geneoes, apologies for the late reply. In general, yes - you can build a URL using this `${giphyId}/giphy.web` template, but not all gifs support `webp` or `mp4` formats, so sometimes this URL will point to 404. I would recommend using the [Giphy JS Fetch API](https://github.com/Giphy/giphy-js/blob/master/packages/fetch-api/README.md#gif-by-id) with [Giphy JS Utils](https://github.com/Giphy/giphy-js/tree/master/packages/util). For example, you can get GIF by id and find the best rendition for your media:
```
import { GiphyFetch } from "@giphy/js-fetch-api";
import { getBestRenditionUrl } from "@giphy/js-util";

const gf = new GiphyFetch("<GIPHY_API_KEY>");

async function getGifUrlById(id) {
  const result = await gf.gif(id);
  return getBestRenditionUrl(result.data, 400, 400, { useVideo: true });
}

getGifUrlById("<GIF ID>");
```

**Comment by giannif** [comment]
@geneoes - as @pshoniuk  mentioned it would be good to use the [getBestRenditionUrl](https://github.com/Giphy/giphy-js/blob/master/packages/util/src/gif-utils.ts#L72) util, as it can give you the best rendition for the size specified as well detect webp support. If webp isn't supported, it displays a gif

**Comment by geneoes** [comment]
Ohh I see, I'll try that then, thanks both!
