### ISSUE TITLE
Gif does not support keypress event

### ISSUE THREAD

**Issue by robertpin** [Giphy/giphy-js#275]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a Gif component is focused and the user presses a key nothing happens

### Expected behavior 🤔

When a Gif is focused and the user presses a key there should be a callback like onGifClick.
This would be good for accessibility. Instead of having to click a Gif the user could just press enter and trigger the same behavior

### Steps to reproduce 🕹

-

### Platform 🌍

All

### GIPHY-JS SDK version

5.4.0

**Comment by pshoniuk** [comment]
Hey @robertpin! Thanks for your work, I'll take a look soon.

**Comment by pshoniuk** [comment]
New versions with support for keypress events released:
 * [@giphy/js-components 5.4.0](https://www.npmjs.com/package/@giphy/js-components/v/5.4.0)
 * [@giphy/react-components 5.6.0](https://www.npmjs.com/package/@giphy/react-components/v/5.6.0)
 
 Thanks to @robertpin for working on this feature.
