### ISSUE TITLE
At Grid component: "Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method."

### ISSUE THREAD

**Issue by Amirbarzegari** [Giphy/giphy-js#277]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using Grid component with the search function, I'm getting the below error whenever a new search term is entered:

"Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    at Grid"

### Steps to reproduce 🕹

I'm only using Grid component with custom search input (no SearchContextManager) and passing the search term as states.

### Platform 🌍

- all devices and browsers

### GIPHY-JS SDK version

@giphy/react-components: ^5.4.0

### Additional context 🔦

I tried using a debouncer but still got the same error. (the same error happens in your own example here https://github.com/Giphy/giphy-js/issues/56#issuecomment-606099213)
I also tried using AbortController() in reques.ts, it didn't solve the issue.

**Comment by pshoniuk** [comment]
Hi @Amirbarzegari, thanks for reaching out. This should be fixed in [@giphy/react-components 5.6.0](https://www.npmjs.com/package/@giphy/react-components/v/5.6.0)
