### ISSUE TITLE
Why there is no 'clips' type?

### ISSUE THREAD

**Issue by artemsvirskyi** [Giphy/giphy-js#292]
In Giphy docs there is [Clips](https://developers.giphy.com/docs/clips) section.

In [Type Option](https://github.com/Giphy/giphy-js/tree/master/packages/fetch-api#type-option) of Fetch API there is 'videos' type, though there is no 'videos' content type in [docs](https://developers.giphy.com/docs/sdk#content-types).

Are 'clips' and 'videos' the same type? If not, what is the difference and why it's not listed in docs, and why there is no 'clips' type?

**Comment by giannif** [comment]
@artemsvirskyi type `videos` is the same as clips. Clips is what we branded our videos as, but the rest api had a more generic term `videos`, and so our js fetch api just sticks with what the backend api uses. Hope that clarifies things! Sorry about the confusion, I wish there was more consistency as well
