### ISSUE TITLE
Carousel does not pass noLink property

### ISSUE THREAD

**Issue by PatrickMalara** [Giphy/giphy-js#296]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Passing Object with noLink property to renderCarousel() still renders Gifs with anchor tags.

link to codepen, add noLink property and set it to true: [codepen](https://codesandbox.io/s/giphy-js-components-forked-q45uo1?file=/src/carousel.ts)

```import { renderCarousel } from "@giphy/js-components";
import { GiphyFetch } from "@giphy/js-fetch-api";

const gf = new GiphyFetch("sXpGFDGZs0Dv1mmNFvYaGUvYwKX0PWIh");
const fetchGifs = (offset: number) => gf.trending({ offset, limit: 4 });

export const vanillaJSCarousel = (mountNode: HTMLElement) => {
  renderCarousel(
    {
      gifHeight: 200,
      user: {},
      fetchGifs,
      noLink: true,
      gutter: 6
    },
    mountNode
  );
};```

### Expected behavior 🤔

When passing `noLink: true` Gifs should render without anchor tags.

### Steps to reproduce 🕹

Steps:

1. call the renderCarousel function
2. pass in an Object with a noLink property


### Screenshots or Videos 📹

_No response_

### Platform 🌍

- OS [MacOS]
- browser [chrome]

### GIPHY-JS SDK version

"@giphy/js-brand": "1.1.7",     "@giphy/js-components": "3.0.5",     "@giphy/js-fetch-api": "1.5.9",     "@giphy/js-types": "2.0.1",     "@types/throttle-debounce": "1.1.1",

### TypeScript version

_No response_

### Additional context 🔦

_No response_

**Comment by giannif** [comment]
@PatrickMalara the latest version of `@giphy/js-components` is `5.5.0`, looks like you're on `3.0.5`

You should see `noLink` work okay after upgrading. 

I updated our codesandbox just to be sure, you can inspect and see there is no a tag: 
https://codesandbox.io/s/1wq52x1w44?fontsize=14&file=/src/carousel.ts

I'd update all of your package versions to avoid issues with types.
