### ISSUE TITLE
Error loading giphs

### ISSUE THREAD

**Issue by josvegit** [Giphy/giphy-js#32]
![Screenshot from 2020-02-06 22-13-05](https://user-images.githubusercontent.com/24354568/73979117-e2769680-492d-11ea-98fd-44a6ab67646e.png)

Getting above

![Screenshot from 2020-02-06 22-13-56](https://user-images.githubusercontent.com/24354568/73979186-fde1a180-492d-11ea-94be-2f83548c8b76.png)

Any idea?

![Screenshot from 2020-02-06 22-14-43](https://user-images.githubusercontent.com/24354568/73979267-223d7e00-492e-11ea-9c7e-79ff534a8898.png)

Seems something works.. getting a 200 ok

**Comment by giannif** [comment]
@josvegit I'm going to look at when I show that message first thing tomorrow. I think it shows if there are no gifs, which isn't really an error, just no results, making this a UI problem 

If you fetch gifs and there are results, everything is okay?

If this helps, here is a codesandbox demonstrating a search for dog gifs:
https://codesandbox.io/s/giphyreact-components-hbmcf?from-embed

**Comment by giannif** [comment]
@josvegit I can't seem to make sense of this, you can see in this line that the error state is only set when the fetch throws:
https://github.com/Giphy/giphy-js/blob/master/packages/react-components/src/components/grid.tsx#L116

Maybe you can add a handler `onGifsFetchError` and see what the error is. 
Also, just making sure you're on the latest version which is `0.3.7`

**Comment by josvegit** [comment]
Console logged the error from **onGifsFetchError**

![Screenshot from 2020-02-07 20-17-15](https://user-images.githubusercontent.com/24354568/74058711-e31f3380-49e6-11ea-87bf-909499bd961d.png)



Also getting a warning from the console 

![Screenshot from 2020-02-07 20-18-19](https://user-images.githubusercontent.com/24354568/74058770-09dd6a00-49e7-11ea-86f1-59002c90862a.png)

**Comment by giannif** [comment]
@josvegit ah! I see. Thanks for the logs 👍 There's an actual error parsing the data. I don't think the request is valid even though it returns a `200`. Can you make sure you're passing a `string` to `giphyFetch.search(search)`, it's typed as `any` and it looks like in the request the value for `q` (as in query) is `q%5Bsearch%5D`. It should be something like `q=dogs`

**Comment by josvegit** [comment]
aah thanks, my bad !
