### ISSUE TITLE
Focused Gif is not visually emphasized

### ISSUE THREAD

**Issue by LBBO** [Giphy/giphy-js#326]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When a Gif is focused, it can't be visually differentiated from other Gifs, e.g. in a Grid. In fact, the browser behavior that would add this functionality by default is explicitly deactivated:

https://github.com/Giphy/giphy-js/blob/3a0a25082f7d49d2d2a0c05de67f6476f306b437/packages/react-components/src/components/gif.tsx#L25
https://github.com/Giphy/giphy-js/blob/3a0a25082f7d49d2d2a0c05de67f6476f306b437/packages/react-components/src/components/gif.tsx#L25

### Expected behavior 🤔

A focused Gif should be visually emphasized.

### Steps to reproduce 🕹

Steps:

1. Open [this sandbox](https://codesandbox.io/s/giphy-react-components-forked-w1jyjt?file=/src/index.tsx)
2. Click on the search box
3. Try to focus on the fourth Gif in the first column only using the Tab key

### Platform 🌍

macOS, Chrome

### GIPHY-JS SDK version

@giphy/react-components@6.2.0

### Additional context 🔦

I'm happy to create a PR for this issue myself, but I'll need to know roughly how you'd like the focussed Gif to be styled. Also, I'd appreciate it if you could let me know of any tricky details to look out for.

**Comment by LBBO** [comment]
@giannif Sorry for the ping, but could I ask for a quick comment on this? Maybe a wontfix or a rough estimate when this might be considered? Also, just to re-iterate: if you let me know what the focussed GIF should look like, I'm more than happy to implement this myself.

**Comment by aar0n1998** [comment]
Hello, just wondering when this would be looked at. This has been raised in an external accessibility audit for us and would be good to know if it's in the works or won't be fixed.
Thanks 😄

**Comment by giannif** [comment]
@aar0n1998 I'll follow up this week. Thanks for your patience
