### ISSUE TITLE
Remove Grid not working

### ISSUE THREAD

**Issue by OmarSadat6** [Giphy/giphy-js#332]
Hi, I wanted to know how to repopulate the grid when an input changes. I can fetch the differents gifs from the search but my grid content is not changing.

**Comment by giannif** [comment]
@OmarSadat6 the approach for this is to use a `key` on the Grid when the input changes: https://codesandbox.io/s/giphyreact-components-search-example-0yrur

This in the documentation, but it's hidden in the examples and not really called out. @pshoniuk maybe we can try to call this out as it's not obvious. Doing this without the `key` approach inside the component would involve diffing the gifs based on their ids and then manually resetting the state to remove all the gifs fetched.  The `key` lets us do this without that overhead 

@OmarSadat6 feel free to reopen if this doesn't solve your problem
