### ISSUE TITLE
It is advised to avoid ship styled-components in the build bundle.

### ISSUE THREAD

**Issue by M-ZubairAhmed** [Giphy/giphy-js#411]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

- `styled components` is a dependency of the library https://github.com/Giphy/giphy-js/blob/master/packages/react-components/package.json#L83

### Expected behavior 🤔

- As per documentation of styled-components it is encouraged that the library be a peer dependency https://styled-components.com/docs/faqs#i-am-a-library-author.-should-i-bundle-styled-components-with-my-library

### Steps to reproduce 🕹

Steps:

1. Add 'giphy/react-components' to existing codebase which uses `styled-component v5`
2. Observe the app breaks because of the library uses v6 while app uses v5
3.

### Platform 🌍

- Chrome v115

### GIPHY-JS SDK version

@giphy/react-components": "8.1.0"

### TypeScript version

4.7.4

### Additional context 🔦

- I understand this would be a breaking change and more suitable for major version release

**Comment by giannif** [comment]
@M-ZubairAhmed thanks for reporting. We're using v5 on giphy.com and v6 in the library and did not experience this issue. I think it's because we have a resolutions field in the root of our monorepo. I'll look into releasing this this week, definitely want to do what's advised

**Comment by giannif** [comment]
@M-ZubairAhmed I have a PR for this and can release it later today. You said in the description this is a breaking change, and I'm wondering why. Could you elaborate on what could break by moving to a peer dependency? I'm wondering about turbo repo prune, but assuming it will be okay

**Comment by M-ZubairAhmed** [comment]
> @M-ZubairAhmed thanks for reporting. We're using v5 on giphy.com and v6 in the library and did not experience this issue. I think it's because we have a resolutions field in the root of our monorepo. I'll look into releasing this this week, definitely want to do what's advised

Yes we were able to mitigate the issue with webpack resolutions as well https://github.com/mattermost/mattermost/pull/24236/files#diff-62d53fdbc012d5c1f572351f3ada24e93a4ab11a45cc7be4b7997162a4939df1R136

**Comment by giannif** [comment]
@M-ZubairAhmed thanks for the feedback. Wasn't exactly sure if peer deps still needed to be installed separately, npm 7 and up does it automatically. yarn doesn't seem to though. pnpm does seem to install them. To play it safe I will make it a major release
