### ISSUE TITLE
Next.js build fails: "Module not found: Can't resolve 'styled-components'" 

### ISSUE THREAD

**Issue by MaxAst** [Giphy/giphy-js#417]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I build my nextjs app, I fails with this error:

```
Failed to compile.

../../node_modules/@giphy/react-components/dist/esm/index.js:58:0
Module not found: Can't resolve 'styled-components'

https://nextjs.org/docs/messages/module-not-found
```

### Expected behavior 🤔

The build shouldn't not fail if I do not use styled-components. I can fix the error by installing styled-components, but it should work without explicitly installing it in my app.

### Steps to reproduce 🕹

Steps:

1. npx create-next-app@latest
2. install @giphy/react-components
3. yarn/npm build

### Platform 🌍

- OS: MacOS

### GIPHY-JS SDK version

@giphy/react-components 9.0.1

### TypeScript version

v5.1.6

**Comment by giannif** [comment]
@MaxAst this is due to moving styled components to peerDependencies #411. Which package manager are you using? I was hoping to avoid this but I don't think there is a way to have styled components as a peer dep and to not have install it

**Comment by MaxAst** [comment]
I'm using yarn v3.6.1
