### ISSUE TITLE
Support for External GIFs

### ISSUE THREAD

**Issue by thomasstep** [Giphy/giphy-js#460]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

I noticed the `externalGifs` array in the [`Grid` component](https://github.com/Giphy/giphy-js/blob/3abfa7c4604ffc471083051de6310ba36c41280f/packages/react-components/src/components/grid.tsx#L31). If this is working as I interpret it, I feel like I should be able to point the component at an external URL and have that GIF show up in my Grid. From what I can tell, this is not the case. Are there any examples of how to use this? If it doesn't work, is there a possibility to add that in?

### Motivation 🔦

I would like to create a Grid of Giphy and custom GIFs.

**Comment by giannif** [comment]
@thomasstep this property hoists the state of the Grid component so it can be manipulated outside of the Grid  component. For example, if you wanted to remove a gif from the grid, you could filter the  `externalGifs` array to not include that gif. 

As far as external URLs, you could technically alter the data to point to different image URLs, but it's not just one URL you'll need to change, you'd have to recreate the `IGif` interface and set all the renditions / dimensions etc. These React Components are tightly coupled to the GIPHY data they represent

**Comment by thomasstep** [comment]
Doesn't sound too feasible to me. If this is out of scope for this library, feel free to close it out.

**Comment by giannif** [comment]
Closing: There may be work in 2025 to support something like this. Will comment here if it's pursued
