### ISSUE TITLE
React Grid with Search

### ISSUE THREAD

**Issue by happylinks** [Giphy/giphy-js#56]
Hi, thanks for these components!
I was trying to implement the Grid with search, so each time an input changes its value, the Grid should fetch.
Do you have an example of how to do this?
I tried to add key={searchTerm} to the grid but then I got a lot of state-updates that went wrong because old api responses came in.

UI for reference:
![image](https://user-images.githubusercontent.com/184774/77827920-be0e8d80-7118-11ea-9d33-4ba068ba427d.png)

**Comment by giannif** [comment]
@happylinks I whipped up an example for you, I was actually thinking about doing this, figuring people would want to see it, thanks for pointing it out! 

https://codesandbox.io/s/giphyreact-components-search-example-0yrur

I'll probably refine it a bit, I'm using hooks and a debounced input, hope it's clear

**Comment by happylinks** [comment]
Thanks a lot! I think using your useDebounce hook fixed it. I was using a different debouncer(https://github.com/MinimaHQ/re-debouncer) that kind of behaved weirdly.
