### ISSUE TITLE
Adblock Pingback

### ISSUE THREAD

**Issue by happylinks** [Giphy/giphy-js#57]
![image](https://user-images.githubusercontent.com/184774/77829311-8b1cc780-7121-11ea-863e-da8eda5b8d91.png)
Seems like pingback calls will be caught in adblock.  
Not sure if there's anything you want to do against this, but thought I'd ask.

**Comment by giannif** [comment]
@happylinks yeah there's nothing we can do here, thanks though!

**Comment by happylinks** [comment]
Hey @giannif, actually I think this library should catch the error and ignore it. Now it's an uncaught error that will end up in our error logs.

**Comment by happylinks** [comment]
PR: https://github.com/Giphy/giphy-js/pull/88
