### ISSUE TITLE
Giphy js Grid

### ISSUE THREAD

**Issue by colorgold** [Giphy/giphy-js#65]
I am using the @giphy/js-components for my project. I implemented a search bar like this:
![searchDogs](https://user-images.githubusercontent.com/45986859/78414782-6756f700-75e3-11ea-9095-36cbaa6b1671.JPG)

However, everytime I search for something, it does not clear the old search but populates below it.
This is an example:
![image](https://user-images.githubusercontent.com/45986859/78414961-670b2b80-75e4-11ea-98f6-a69e81cc7faa.png)

I am using the "remove" function to remove the grid contents before performing a search
`remove() {`
    `if (this.el) {`
     ` this.el.parentNode.removeChild(this.el);`
     ` window.removeEventListener("resize", this.resizeRender, false);`
     ` this.el = null;`
   ` }`
 ` }`

This is how I fetch the gifs:
`export class VanillaJSGrid {`
 `mountNode: HTMLElement;`
  `el: HTMLElement;`
 ` resizeRender;`
 ` constructor(mountNode: HTMLElement, input: string) {`
    `this.mountNode = mountNode;`
    `inputSearch = input;`
       `this.resizeRender = throttle(500, () => this.render());`
        `window.addEventListener("resize", this.resizeRender, false);`
      ` this.render();`
`  }`

  `render = () => {`
   ` const width = getWidth();`
    
   ` this.el = renderGrid(`
      `{`
       ` width,`
        `fetchGifs,`
       ` columns: width < 500 ? 2 : 3,`
        `gutter: 6,`
        `user: {},`
        `onGifClick: gif => console.log(gif.url)`
     ` },`
     ` this.mountNode`
    `) as HTMLElement;`
  `};`
  `remove() {`
   ` if (this.el) {`
      `this.el.parentNode.removeChild(this.el);`
     ` this.el = null;`
    `}`
  `}`

  `searchGifs(look: string) {`
    `this.remove();`
    `inputSearch = look;`
    `fetchGifs = (offset: number) => gf.search(look, { offset, limit: 10 });`
   ` this.render();`
  `}`
`}`

How to I reset the search using the JavaScript SDK?

**Comment by giannif** [comment]
@colorgold the problem is in my `renderGrid` function, something is happening with `Preact` and the virtual DOM that I didn't expect. I'll need to use a `key` so the virtual dom knows to destroy and recreate the component

```typescript
export const renderGrid = (gridProps: Grid['props'], target: HTMLElement): Element => {
    render(<Grid {...gridProps} key={"I need to change the key here"} />, target)
    return target.querySelector(`.${gridProps.className || Grid.className}`)!
}
```

I'll work on a fix

**Comment by giannif** [comment]
@colorgold actually looks like I don't need to add any code, you can already pass a `key` to  `renderGrid`.  I may do a release where every time you invoke `renderGrid`, it generates a new key, but I want to think about that a little. Thanks for catching this!!

```typescript
this.el = renderGrid({
    width,
    fetchGifs,
    columns: width < 500 ? 2 : 3,
    gutter: 6,
    user: {},
    onGifClick: gif => console.log(gif.url)
    key: 'your search term is a good key'
}

**Comment by colorgold** [comment]
> ```ts
> key: 'your search term is a good key'
> ```

Thank you so much! I added passed `key` to `renderGrid` and it worked.
