### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by devpascoe** [Giphy/giphy-js#67]
Something to look into is React Native support. Unable to get an iOS app running, comment out import { GiphyFetch } from '@giphy/js-fetch-api' and i am working again. Can use urls directly for now.
The issue was a build error in Xcode indicating "Can't find variable location".

**Comment by giannif** [comment]
Thanks @devpascoe !  When you say working again, what do you mean is working?

**Comment by devpascoe** [comment]
Working as in the Xcode project will build again.

**Comment by giannif** [comment]
@devpascoe gotcha. We're a bit off in developing this, we'll have a new `@giphy/react-native-components` library and everything.  Excited to work on it though, hopefully soon 🤞

**Comment by devpascoe** [comment]
Fun! Getting by with using your urls directly for now. 👍

**Comment by banatiarpit97** [comment]
Facing the same issue with Android app as well.

**Comment by giannif** [comment]
@banatiarpit97 don't forget we do have native SDKs: https://developers.giphy.com/docs/sdk#android React Native SDK isn't currently being worked on, but it is on the roadmap

**Comment by banatiarpit97** [comment]
Yes, I know about the Android SDK but integrative native SDK on a react native app would be a tedious task for me. Directly hitting Giphy URLs seems an easier option right now.
Anyways, excited to see a React Native SDK in future.

**Comment by destinybonavita** [comment]
Has anyone had any luck getting `@giphy/js-fetch-api` working in React Native?

**Comment by giannif** [comment]
@destinybonavita can you see where `location` is being referenced? There isn't anything in the [giphy/js repo](https://github.com/Giphy/giphy-js/search?q=location&unscoped_q=location) that looks problematic to me. It could be a dependency though

**Comment by destinybonavita** [comment]
@giannif I didn't see anything in the repo that could of been causing it. I searched my entire repo, `node_modules` included, for `location` but couldn't find anything. I eventually just decided to use the REST API.

**Comment by giannif** [comment]
@destinybonavita thanks for giving it a shot. React Native support is on our roadmap. Stay tuned

**Comment by shreesh5** [comment]
Has anyone found a workaround to make `@giphy/js-fetch-api` work with React-Native?
I'm getting the same "Can't find variable: location" error. Is there any way to integrate the native Android/iOS SDKs and use them in React-Native?

**Comment by szymonograbek** [comment]
I've just worked on giphy picker for react native and to make it work you need to make changes in the following files:
-  `get-pingback-id.js` in `js-utils` - react native doesn't have `sessionStorage` so as a workaround you can just check if the sessionStorage exists and if it doesn't generate new `pingbackId` without saving it
- `log.js` in `js-utils` - to enable the `Logger` it uses `location` which is not available in react native so as a solution you need to add an additional check `typeof location !== 'undefined'`

**Comment by giannif** [comment]
@szymonograbek thanks for digging in here, I'm going to make the changes and do a release. Confused though about what I can do for `sessionStorage`, is there an error thrown? It looks like everything is a in a try catch and pingback id should still be stored in memory

**Comment by szymonograbek** [comment]
@giannif Oh, that's true, I didn't notice the try/catch block. The change with checking if `sessionStorage` exists is not needed, but you need to follow this [https://github.com/uuidjs/uuid#getrandomvalues-not-supported](https://github.com/uuidjs/uuid#getrandomvalues-not-supported) as `getRandomValues` in `uuid` is not supported in react-native

**Comment by giannif** [comment]
Good news everyone, we have an official React Native SDK coming soon. If you'd like to request access to the limited beta, email sdk@giphy.com and include your github user name
