### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by happylinks** [Giphy/giphy-js#68]
Hi, not sure if I'm doing an import wrong or something, but I'm getting this error in my build-process:
```
[ warn ]  ./node_modules/@giphy/js-brand/dist/index.js
Critical dependency: the request of a dependency is an expression
```

**Comment by giannif** [comment]
@happylinks this is an issue with the parcel bundler we use to bundle our packages, I tried to resolve it last year but never got anywhere. 

https://github.com/parcel-bundler/parcel/issues/2883#issuecomment-489771794

Not sure if anything has changed, the ticket is still open

If you're using webpack, I have a comment in the above thread on how to turn the warning off.

**Comment by happylinks** [comment]
Thanks, adding your "fix" to turn the warning off worked 👍 
```// @giphy/js-brand uses parcel-bundler which has require statements
new webpack.ContextReplacementPlugin(/\/@giphy\/js-brand\//, data => {
  delete data.dependencies[0].critical
  return data
}),```
I'll be following that thread to see if they'll find a better fix :)
