### ISSUE TITLE
Search stickers

### ISSUE THREAD

**Issue by banatiarpit97** [Giphy/giphy-js#69]
Following the readme file on the repo, I am not able to search for stickers.

My Code:
   import { GiphyFetch } from '@giphy/js-fetch-api'
   const gf = new GiphyFetch('your api key');
   const { data: gifs } = await gf.search('dogs', { sort: 'relevant', lang: 'es', limit: 10, type: 'sticker' })

I am getting a 404 error.
API call made by SDK has the following URL:
https://api.giphy.com/v1/**sticker**/search?sort=relevant&lang=es&limit=10&type=sticker&q=dogs&api_key=MY_KEY

But if I try the API explorer on Docs page of Giphy, URL to search the stickers should be:
https://api.giphy.com/v1/sticker**s**/search?sort=relevant&lang=es&limit=10&type=sticker&q=dogs&api_key=MY_KEY

There is a 's' missing in the URL of API calls made by SDK.

**Comment by giannif** [comment]
@banatiarpit97 darn, that's an error in the README, the [type]()https://github.com/Giphy/giphy-js/blob/master/packages/fetch-api/src/option-types.ts#L4) value is `stickers`. 

I will update the README, sorry about this!

**Comment by banatiarpit97** [comment]
Changing the type from 'sticker' to 'stickers' worked for me. Thanks.
