### ISSUE TITLE
@giphy/js-components Compiling to Javascript

### ISSUE THREAD

**Issue by colorgold** [Giphy/giphy-js#72]
I have a website that I have only used JavaScript with, but I tried using TypeScript as per the example on CodeSandbox. The problem I am having is that the browsers are not compiling the code correctly. Some of the errors I have encountered are:
"chat.ts” was blocked because of a disallowed MIME type (“video/mp2t”)" `//chat.ts is basically the same code as index.ts in the CodeSandbox example`
After installing TypeScript through npm and creating the js files I get this error:
"ReferenceError: exports is not defined" in chat.js (source of error:` Object.defineProperty(exports, "__esModule", { value: true });`) This code was generated by running tsconfig.json in Visual Studio Code

I know how to program with TypeScript, but the problem is that I don't know how to compile in the browser. I've tried researching this but had no luck. What am I missing?

**Comment by giannif** [comment]
@colorgold you can use the [TypeScript Compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html) 

It's how we compile most of the code in this repo.

You'll just do: 
```bash
tsc index.ts
```

Then the rest of the configuration comes from the tsconfig.json. Here is our [tsconfig.json](https://github.com/Giphy/giphy-js/blob/master/tsconfig.json)

**Comment by colorgold** [comment]
> @colorgold you can use the [TypeScript Compiler](https://www.typescriptlang.org/docs/handbook/compiler-options.html)
> 
> It's how we compile most of the code in this repo.
> 
> You'll just do:
> 
> ```shell
> tsc index.ts
> ```
> 
> Then the rest of the configuration comes from the tsconfig.json. Here is our [tsconfig.json](https://github.com/Giphy/giphy-js/blob/master/tsconfig.json)

Thank you for your response and patience. In my html file, do I reference the `index.ts` script or `index.js`? I copied the `tsconfig.json` you provided me with but I'm still having problems. For now I will go read the documentation on TypeScript Compiler to learn how to use it. Thanks again for the information.

**Comment by giannif** [comment]
@colorgold no problem! you'd reference the `index.js` from you html script src.

**Comment by colorgold** [comment]
> @colorgold no problem! you'd reference the `index.js` from you html script src.

I installed the TypeScript compiler but now I get a different error. This is what my code looks like:
![image](https://user-images.githubusercontent.com/45986859/78951421-be534500-7a97-11ea-8ad7-5a696cf0cc35.png)

![image](https://user-images.githubusercontent.com/45986859/78951441-d1feab80-7a97-11ea-8afc-a69a88b1fb6f.png)

If I remove the 2nd line in chat.js, I then get this error:
![image](https://user-images.githubusercontent.com/45986859/78951527-14c08380-7a98-11ea-97ba-d4c65644e537.png)

I don't know what I am doing wrong. I have read that putting a dummy `var exports` and `var require` works, but as expected, it did not load GIFs.

**Comment by giannif** [comment]
Ah I may have mislead you about `tsc`, we use that for our repo, but that is for our libraries, not for a bundle you'd use in a web page. 

Take a look at https://parceljs.org/ 

It should be easy to get the bundled file you need for use with a script tag.

**Comment by colorgold** [comment]
> Ah I may have mislead you about `tsc`, we use that for our repo, but that is for our libraries, not for a bundle you'd use in a web page.
> 
> Take a look at https://parceljs.org/
> 
> It should be easy to get the bundled file you need for use with a script tag.

Would I still need `tsc` or do I get rid of all the `js` files created? I will go ahead and use parcel and see what happens. Thank you!

**Comment by colorgold** [comment]
Thank you for recommending me `Parcel`. I was using webpack before and was getting so confused. So, the problem that I was having was that I was using my own server since I am also working with `Firebase hosting`. `Parcel` created a directory named `dist`, but my server serves files under my `public` directory; every time I ran my web app I got errors because the browser did not have access to the `dist` directory. I was able to catch my mistake by creating a new project in `Visual Studio Code`. I ran the project in the server that `Parcel` gave me and voila, the `Giphy carousel` loaded successfully. Now all I have to do is organize my original project.

Thank you so much for helping me and guiding me to solve my problem.

**Comment by maltoze** [comment]
> Ah I may have mislead you about `tsc`, we use that for our repo, but that is for our libraries, not for a bundle you'd use in a web page.
> 
> Take a look at https://parceljs.org/
> 
> It should be easy to get the bundled file you need for use with a script tag.

Why doesn't provide a version that can be used directly in `<script>`?

**Comment by giannif** [comment]
@maltoze it's possible, just most people use a bundler and it hasn't been on our roadmap. I'd have to add a `umd` file to our package.json and then it looks like you'd be able to use https://unpkg.com/ to grab the code in a script tag
