### ISSUE TITLE
XSS vulnerability in linked library

### ISSUE THREAD

**Issue by Auretus** [Giphy/giphy-js#77]
TL;DR - your linked version of dompurify has a XSS vulnerability, updating to >=2.07 should fix it.
Got this report when I installed your package for a personal project:

                       === npm audit security report ===                            

  Critical        Cross-Site Scripting                                          
  Package         dompurify                                                     
  Patched in      >=2.0.3                                                       
  Dependency of   @giphy/js-components                                          
  Path            @giphy/js-components > @giphy/js-analytics > dompurify
  More info       https://npmjs.com/advisories/1205

  Critical        Cross-Site Scripting
  Package         dompurify
  Patched in      >=2.0.7
  Dependency of   @giphy/js-components
  Path            @giphy/js-components > @giphy/js-analytics > dompurify
  More info       https://npmjs.com/advisories/1223

**Comment by giannif** [comment]
This was an unused dependency in our package.json, it was removed
