### ISSUE TITLE
Giphy-js compiles with warnings using Webpack

### ISSUE THREAD

**Issue by thibault-yellowstones** [Giphy/giphy-js#85]
Please find below an extract of my terminal while running `npm start` in a `create-react-app` project.

```
Compiled with warnings.

./node_modules/@giphy/js-brand/dist/index.js
Critical dependency: the request of a dependency is an expression
```

This is a problem, as project builds will fail because of this.
It does not look like a big issue to solve. But it would be really helpful. Thanks.

**Comment by giannif** [comment]
Hey @thibault-yellowstones this is just a warning, and it should not fail project builds, if you want to suppress the warning, you can (see #68)
