### ISSUE TITLE
Missing Callbacks "onGifsFetched" and "onGifsFetchError" in web SDK

### ISSUE THREAD

**Issue by kmschott** [Giphy/giphy-js#92]
The callbacks `onGifsFetched` and `onGifsFetchError` for the web SDK in the js-components especially in the `renderGrid` function are optional and not called if the `fetchGifs` function does not return anything.

This makes it currently impossible for me to check and display a hint, if the query does not return any results.

I use Vue.js instead of React and therefore the native web components. I use it like this:

```js
const fetchGifs = new GiphyFetch(apiKey).search(query, { ... })

renderCarousel({
    fetchGifs,
    onGifsFetched: (gifs) => {
        ...
    },
    onGifClick: (gif, event) => {
        ...
    },
    ...
})
```

* "@giphy/js-components": "^3.0.5"
* "@giphy/js-fetch-api": "^1.5.9"

**Comment by kmschott** [comment]
Thanks! This kind of works. I needed some small adjustments and `gifs` are not returned in the result, instead we need to check for `result.data.length <= 0`. Thus, I also added proper error handling with a try-catch-block, because I stumbled across the `result.gifs.length` not found.

**Comment by giannif** [comment]
@kmschott you want to check `result.data` for sure.  `result.gifs` is wrong, my bad

**Comment by giannif** [comment]
We're going to add a `noResultMessage` property thanks to this PR #91  
This will make it easier to display a message when there are no results, and you won't have to wrap the fetch anymore once we release
