### ISSUE TITLE
giphyRandomId undefined

### ISSUE THREAD

**Issue by alokjkumar** [Giphy/giphy-js#93]
The giphyRandomId variable is undefined as needed for the verification process:
https://developers.giphy.com/docs/sdk#verification

Using Angular 9.1.0

**Comment by giannif** [comment]
@alokjkumar can you tell me which package and version you're using? If you're using Angular, I'm guessing you're using `@giphy/js-components`. Make sure you have the latest version. You can see the `giphyRandomId` here in the console here in this [codesanbox](https://codesandbox.io/s/1wq52x1w44), it's defined globally

**Comment by alokjkumar** [comment]
Just using @giphy/js-fetch-api@^1.5.9 and populating my own custom UI

**Comment by giannif** [comment]
@alokjkumar I'm going to close this since you're only using the fetch api and analytics and the random id don't apply in that scenario. I'm going to talk to the team and make sure we document this, you're not the first person to ask this

**Comment by alokjkumar** [comment]
@giannif thanks for the help. I've done some looking into the components library and I think I can apply most of my custom styling from a global stylesheet

**Comment by giannif** [comment]
@alokjkumar no problem. We have two layout components, `Carousel` and `Grid`. If you need a custom layout, you can still use the `Gif` and wrap it in an element and style it as needed. Or you can target the root element className of the `Gif` with [.giphy-gif](https://github.com/Giphy/giphy-js/blob/master/packages/components/src/components/gif.tsx#L284)

**Comment by ayyar** [comment]
@giannif how does one request verification if we are using the fetch API?

Right now the steps for verification here require giphyRandomId.
https://developers.giphy.com/docs/sdk/#verification

**Comment by giannif** [comment]
@ayyar if you're not using UI components and only using the fetch api, then there is no verification. You just need a production ready api key and would reference the api section, not the sdk section: https://developers.giphy.com/docs/api#quick-start-guide
