### ISSUE TITLE
React Build Fails - Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by TobyDGosselin** [Giphy/giphy-js#96]
When building my react app using the default react-scripts production build I get failures in CI due to the following:
```
2:42:54 PM: Failed to compile.
2:42:54 PM: 
2:42:54 PM: ../node_modules/@giphy/js-brand/dist/index.js
2:42:54 PM: Critical dependency: the request of a dependency is an expression
2:42:54 PM: error Command failed with exit code 1.
```

Investigation has lead me to believe this is an issue with the giphy-js modules being bundled with parcel and CRA using webpack. Any suggestions on how to fix this?

**Comment by giannif** [comment]
@TobyDGosselin this is usually a warning, and does not cause the build to fail, see #68 

You can follow the steps there to remove the warning, but I think the error might be something else

**Comment by TobyDGosselin** [comment]
@giannif I am not sure where to put that file.  Do I need to eject my react app for that to work?

**Comment by giannif** [comment]
@TobyDGosselin reference the parcel bundler issue that I linked in the other ticket to remove the warning: https://github.com/parcel-bundler/parcel/issues/2883#issuecomment-489771794

I don’t think this is what is failing your build, this has always just been a warning and does not make builds fail

**Comment by TobyDGosselin** [comment]
@giannif it will fail the build because it is in CI.

```2:41:38 PM: $ react-scripts build
2:41:40 PM: Creating an optimized production build...
2:42:54 PM: 
2:42:54 PM: Treating warnings as errors because process.env.CI = true.
2:42:54 PM: Most CI servers set it automatically.
2:42:54 PM: 
2:42:54 PM: Failed to compile.
2:42:54 PM: 
2:42:54 PM: ../node_modules/@giphy/js-brand/dist/index.js
2:42:54 PM: Critical dependency: the request of a dependency is an expression
2:42:54 PM: error Command failed with exit code 1.
2:42:54 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2:42:54 PM: error Command failed.
2:42:54 PM: Exit code: 1
2:42:54 PM: Command: /opt/buildhome/.nvm/versions/node/v10.21.0/bin/node
2:42:54 PM: Arguments: /opt/build/cache/yarn/lib/cli.js build
2:42:54 PM: Directory: /opt/build/repo/client
```

This is an actual issue and needs to be resolved. I don't want to have to run my release to prod with CI=''

**Comment by giannif** [comment]
@TobyDGosselin okay then you’ll need to remove the warning as described in #68, there’s not much more I can do, it’s an issue with our bundler. I’ve never used create react app, so I can’t advise on whether or not you need to eject. Wish I could help more.

**Comment by giannif** [comment]
This should not be happening at all now with latest version, we are no longer using parcel for bundling our `@giphy/js-brand` repo
