### ISSUE TITLE
hideAttribution flag isn't an input property on js-components renderGrid

### ISSUE THREAD

**Issue by duncan-c** [Giphy/giphy-js#99]
Hey,

I'm trying to disable attribution and gif links on the grid, but typescript is complaining that hideAttribution isn't a valid property in the options object, and I can't see a way of preventing the gifs automatically opening the giphy website?

Thanks!

**Comment by giannif** [comment]
@duncan-c thanks for reporting, looks like I missed adding the property to the grid and carousel there like I did in the react components package. I'll get out a fix soon. As far as stopping the links, you can add an `onGifClick` handler and invoke `e.preventDefault()`

```typescript
onGifClick={(gif, e) => {
  e.preventDefault();
  // do what you want here
}}

**Comment by duncan-c** [comment]
Thanks for the fast response! `preventDefault()` worked perfectly.

**Comment by giannif** [comment]
@duncan-c `@giphy/js-components` version 3.2.1 has the props. It should be available now
